### ISSUE TITLE
Installation on Windows fails

### ISSUE THREAD

**Issue by haesleinhuepf** [royerlab/dexp#117]
Hi @JoOkuma ,

I'm just trying to install dexp on my Windows machine into a clean conda environment. These were the commands I ran:

```
conda create --name dexp python=3.9 napari=0.4.15 -c conda-forge
conda activate dexp
pip install dexp[color,cuda112,napari]
```

And that's the error I'm receiving:
```
ERROR: Could not find a version that satisfies the requirement dexp[color,cuda112,napari] (from versions: none)
ERROR: No matching distribution found for dexp[color,cuda112,napari]
```

Let me know if I can help tracing down the issue.

Best,
Robert

**Comment by JoOkuma** [comment]
Hi, @haesleinhuepf 

Could you try installing it without the `cuda112` option and installing `cupy` `on its own command (e.g., `pip install cupy-cuda112`)?

**Comment by JoOkuma** [comment]
Ok, thanks, I'll update the README and close this issue later.
