### ISSUE TITLE
Different results using the classic and the yang deskew methods

### ISSUE THREAD

**Issue by XarlesMicro** [royerlab/dexp#137]
Hi, I am trying to use DEXP to deskew some images acquired with an OPM. I am getting two vastly different results using the classic and the Yang approaches. To bench mark my script,  I am trying to deskew the 25 microm sphere of an Argo slide imaged with an OPM. While the Yang approach returns a perfect sphere of 25 um (it seems the correct by all the metrics), the classic approach presents two problems: 
1). the sphere is still elongated after deskew. 
2) the result is oversaturated. 

Additional situation: I am having the problem that I have to restart my kernel frequently as it seems that running the script frequently somehow holds VScode to process new commands. I am sending here the script. Any help would be appreciated. 

Additional question: I would like to compare the speed of the numpy vs the cupy backend of DEXP. how can I ask DEXP to use the numpy or the cupy backend? 

> 
> `#%% Import Libraries
> import dexp
> from tifffile import imread
> import numpy as np
> from dexp.processing.deskew import yang_deskew, classic_deskew
> import napari
> 
> #%% Load stack and deskew it by two methods:
> 
> path2img = 'C:\\Python\\Tilt_Calibration_by_Sphere_deskew\\20240207_agoSlide_sphere_8_1_MMStack_Pos0.ome.tif' 
> RawImage = imread(path2img)
> RotatedImage = np.transpose(RawImage, axes=(0, 2, 1)).copy() 
> dz_pixel = 1.0
> test_angle = 45
> 
> dz_stage = dz_pixel / np.sin(np.deg2rad(test_angle))
> 
> deskeweedImg_yang = dexp.processing.deskew.yang_deskew(RotatedImage, 
>                                                   depth_axis = 0, 
>                                                   lateral_axis = 2, 
>                                                   flip_depth_axis = 0, 
>                                                   dx = 0.175, 
>                                                   dz = dz_stage, 
>                                                   angle = 45, 
>                                                   camera_orientation = 0, 
>                                                   num_split = 1, 
>                                                   internal_dtype = None, 
>                                                   padding = None)
> 
> deskeweedImg_classic = dexp.processing.deskew.classic_deskew(RotatedImage, 
>                                                           depth_axis = 0, 
>                                                           lateral_axis = 2, 
>                                                           dx = 0.175, 
>                                                           dz = dz_stage, 
>                                                           angle = 45, 
>                                                           camera_orientation  = 0, 
>                                                           flip_depth_axis = 0, 
>                                                           epsilon = 0.5, 
>                                                           order = 1, 
>                                                           padding = True, 
>                                                           copy = True, 
>                                                           internal_dtype=None)
> deskeweedImg_classic = np.transpose(deskeweedImg_classic, axes=(0, 2, 1)).copy() 
> 
> #%% Display and compare deskew methods using napari
> 
> viewer = napari.Viewer()
> viewer.add_image(deskeweedImg_yang, name='Yang', scale=(dz_stage/0.175, 1, 1)) 
> viewer.add_image(deskeweedImg_classic, name='Classic', scale=(dz_stage/0.175, 1, 1)) 
> napari.run() 
> 

`
![deskew_dexp_classic_yang_napari_comparison](https://github.com/royerlab/dexp/assets/162633308/07ce5f0f-210f-41c2-87f2-e37feba7eaed)

**Comment by JoOkuma** [comment]
Hi @XarlesMicro , I'm glad you're finding `dexp` useful.

The `classic` deskew has a known bug #120 , so I would use only Yang's version. That's what we used in our papers.

I recommend wrapping your code in a main function. You can get issues when you have variables in the global scope and not using `if __name__ == "__main__":`, For example:


```python

def main():
     # your code here


if __name__ == "__main__":
    main()

```

In [here](https://github.com/royerlab/dexp/blob/8e8399f5d0d8f1e1ae0ddfa6cb6011921929ae0b/dexp/datasets/operations/deskew.py#L28) we used the best available backend, in summary, you need to do something like:


```python
from dexp.utils.backends import CupyBackend

...

    with CupyBackend() as bkd:
        cu_array = bkd.to_backend(array)
        cu_array_out = your_cupy_compatible_function(cu_array)
        array_out = bkd.to_numpy(cu_array_out)

...
```

I hope this helps you out

**Comment by XarlesMicro** [comment]
BTW, it works like a charm. Thanks!
