### ISSUE TITLE
Dexp cpu compatibility

### ISSUE THREAD

**Issue by pranathivemuri** [royerlab/dexp#2]
1. It would be great if tensorflow-gpu is not a required installation and all the associated gpu tools. I am working with the commit a9781697ff390b15970b916e4e92f0244fa5f65d that was actually stable and worked symmetrically on fry2 and locally. 

2. The recent package installations in dexp using gputools etc have raised different opencl errors 

clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR on fry2 in converting to tiff files. I had to revert few commits and stop importing the sharpen module and fusion that interact with gputools to make dexp work for me.

**Comment by royerloic** [comment]
ok, will remove these dependencies from the default, the readme will detail which option (opencl) to avoid for this. 
I need to re-implement the volume renderer using cupy instead of using opencl.
