### ISSUE TITLE
Zarr dataset structure

### ISSUE THREAD

**Issue by avenkatramani** [royerlab/dexp#21]
We have a custom built lightsheet microscope. If someone could detail the expected Zarr dataset structure, I could transform our data into it.

**Comment by JoOkuma** [comment]
@royerloic is working on that. It should be available soon.

**Comment by JoOkuma** [comment]
@avenkatramani, if the added information is still not enough, let us know.

**Comment by avenkatramani** [comment]
This is perfect, thanks!
