### ISSUE TITLE
dexp tiff viewer 

### ISSUE THREAD

**Issue by pranathivemuri** [royerlab/dexp#3]
Dexp view should also support tiff dataset viewing.

**Comment by royerloic** [comment]
Good point, we should support a generic TIFF format. This would make it easier to use dexp for other use cases than light-sheet datasets from our custom scopes.

**Comment by JoOkuma** [comment]
Napari supports TIFF files with some of its plugins.

- https://github.com/GenevieveBuckley/napari-tifffile-reader
- https://github.com/tlambert03/napari-ndtiffs
