### ISSUE TITLE
What is the complete command format when running the program?

### ISSUE THREAD

**Issue by ornekofbf** [royerlab/dexp#78]
Sorry to bother you, can you provide us with the complete commands when running the program? For example, which is the main program we should run? When we try to add an image, we cannot execute the add() function by running the following command:
(dexp) g: \ learning \ 3D deconvolution \ dexp master \ dexp master \ dexp \ cli > Python dexp_ main. py add data_ fused. zarr ./ output
We hope you can give us a screenshot or specific description of the running program. Thank you very much!!!

**Comment by JoOkuma** [comment]
Hi @ornekofbf, I'm going to upload a demo tutorial this week on our [documentation page](https://royerlab.github.io/dexp/build/html/index.html).

For now, you could run `dexp --help` and `dexp <command> --help` to check the parameters meaning. There is no need to call `dexp_main.py`.

I'll tag when the tutorial is available.

**Comment by JoOkuma** [comment]
Hi @ornekofbf the example is [here](https://royerlab.github.io/dexp/build/html/how_to_guides/processing_multi_view.html#) let me know if it helps.

**Comment by JoOkuma** [comment]
Hi @ornekofbf, if the tutorial did not resolve your question let me know and I'll re-open this issue.
