### ISSUE TITLE
VolumeRenderer cannot import gputools

### ISSUE THREAD

**Issue by AhmetCanSolak** [royerlab/dexp#9]
Basically similar to #8 , we are missing gputools as a dependency and volumerender submodule cannot import gputools. Will address in a separate PR.

**Comment by royerloic** [comment]
going forward I want to move away from opencl, and reimplement the volume renderer in pure cupy... 
so for now gputools and pyopencl must be installed by 'hand' to be able to use the volume renderer feature.

**Comment by JoOkuma** [comment]
This is not an issue anymore but the docs can't be built with `gputools`. This can be easily fixed, but I rather remove the usage of `gputools` from DEXP.

**Comment by JoOkuma** [comment]
Closing because this was solved by making `gputools` an optional dependency.
